# AppVeyor Configuration for Building tgcrypto on Windows
version: 1.0.{build}

# Environment Variables
environment:
  PYTHON_VERSION: "3.12.0"

# Clone repository
clone_depth: 1

# Install Dependencies
install:
  # Ensure Chocolatey is updated
  - choco upgrade chocolatey -y
  - RefreshEnv

  # Check if Python 3.12 is installed; install only if missing
  - choco list --localonly | findstr python312 || choco install python312 --version=3.12.0 -y
  - RefreshEnv

  # Install required build tools for compiling tgcrypto
  - choco install visualstudio2022buildtools -y
  - choco install visualstudio2022-workload-vctools -y
  - RefreshEnv

  # Verify Python installation
  - python --version
  - python -m pip install --upgrade pip setuptools wheel

# Build tgcrypto
build_script:
  - python -m pip install -r requirements.txt
  - python setup.py bdist_wheel

# Upload built wheels as artifacts
artifacts:
  - path: dist\*.whl
    name: tgcrypto-wheel

# Test Installation (Optional)
test_script:
  - python -m pip install --no-index --find-links=dist tgcrypto
  - python -c "import tgcrypto; print('tgcrypto installed successfully!')"
