# AppVeyor configuration for installing tgcrypto

version: 1.0.{build}

image: Visual Studio 2022

environment:
  PYTHON_VERSION: "3.12"

install:
  # Upgrade Chocolatey
  - choco upgrade chocolatey -y
  - RefreshEnv


  # Install necessary dependencies
  - choco install visualstudio2022buildtools -y
  - choco install cmake -y
  - choco install ninja -y
  - choco install vcredist140 -y
  - RefreshEnv

  # Upgrade pip and install tgcrypto
  - python -m pip install --upgrade pip
  - python -m pip install tgcrypto

test_script:
  # Verify tgcrypto installation
  - python -c "import tgcrypto; print('tgcrypto installed successfully!')"
