# AppVeyor configuration file for building tgcrypto

# Define the environment
environment:
  matrix:
    - PYTHON_VERSION: "3.12.0"

install:
  # Uninstall any previous Python versions to prevent conflicts
  - choco uninstall python --yes
  - choco uninstall python3 --yes
  - choco uninstall python312 --yes
  - RefreshEnv

  # Install Python 3.12.0
  - choco install python312 --version=3.12.0 -y
  - RefreshEnv

  # Verify Python installation
  - python --version
  - pip --version

  # Upgrade pip, setuptools, and wheel
  - python -m pip install --upgrade pip setuptools wheel

  # Install build dependencies
  - python -m pip install cython
  - python -m pip install --upgrade build

  # Clone the tgcrypto repository (or download the source code)
  - git clone https://github.com/pyrogram/tgcrypto.git
  - cd tgcrypto

  # Build the wheel
  - python setup.py bdist_wheel

  # Install the built wheel
  - python -m pip install dist/*.whl

  # Verify installation
  - python -c "import tgcrypto; print('TgCrypto installed successfully')"

artifacts:
  - path: tgcrypto/dist/*.whl
    name: tgcrypto_wheel

build: off  # No separate build step

test_script:
  - python -m unittest discover -s tests
