version: 1.0.{build}

image: Visual Studio 2022

environment:
  PYTHON_VERSION: "3.12"

install:
  # Upgrade Chocolatey
  - choco upgrade chocolatey -y
  - RefreshEnv

  # Install necessary dependencies
  - choco install visualstudio2022buildtools -y
  - choco install cmake -y
  - choco install ninja -y
  - choco install vcredist140 -y
  - RefreshEnv

  # Upgrade pip
  - python -m pip install --upgrade pip

  # Clone tgcrypto repository from Pyrogram GitHub
  - git clone https://github.com/pyrogram/tgcrypto.git C:\projects\tgcrypto

  # Navigate to the tgcrypto directory
  - cd C:\projects\tgcrypto

  # Build the tgcrypto wheel using pip
  - python setup.py bdist_wheel

  # Install tgcrypto
  - python -m pip install tgcrypto

artifacts:
  # Upload the tgcrypto built .whl file from the dist folder
  - path: C:\projects\tgcrypto\dist\*.whl
    name: tgcrypto_wheel

test_script:
  # Verify tgcrypto installation by importing it
  - python -c "import tgcrypto; print('tgcrypto installed successfully!')"
