version: 1.0.{build}

image: Visual Studio 2022

environment:
  PYTHON_VERSION: "3.12"


artifacts:
  # Upload the tgcrypto built .whl file from the dist folder
  - path: C:\projects\tgcrypto_new\dist\tgcrypto-1.2.5-cp312-cp312-win32.whl
    name: tgcrypto_wheel

test_script:
  # Verify tgcrypto installation by importing it
  - python -c "import tgcrypto; print('tgcrypto installed successfully!')"
